name: NetVideo Series

on:
  schedule:
    # CRON ACTUALIZADO: Ejecutar cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # PERMISO DE ESCRITURA (CRUCIAL)
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - run: pip install requests

      - name: Generar Series NetVideo
        env:
          URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }} 
        run: python netvideo_series.py
        
      - name: Generar Peliculas JSON NetVideo
        env:
          URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }} 
        run: python netvideo_json.py

      - name: Generar Series JSON NetVideo
        env:
          URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }} 
        run: python netvideo_series_json.py
        
      - name: Publicar listas en el repo central (Guia)
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot Series"
          
          # 1. Clonar el repositorio central destino
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/TIGRE9725/guia.git temp_repo
          
          # 2. Copiar los archivos generados a la carpeta del repo central (SOLO si pesan más de 1KB)
          if [ -f netvideo.series.m3u ] && [ $(stat -c%s netvideo.series.m3u) -gt 1000 ]; then cp netvideo.series.m3u temp_repo/; else echo "M3U vacío o con error, ignorado."; fi
          if [ -f netvideo_pelis.json ] && [ $(stat -c%s netvideo_pelis.json) -gt 1000 ]; then cp netvideo_pelis.json temp_repo/; else echo "Pelis JSON vacío o con error, ignorado."; fi
          if [ -f netvideo_series.json ] && [ $(stat -c%s netvideo_series.json) -gt 1000 ]; then cp netvideo_series.json temp_repo/; else echo "Series JSON vacío o con error, ignorado."; fi
          
          # 3. Entrar, registrar cambios y empujar al repo de distribución
          cd temp_repo
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Series NV: Listas enviadas a Distribución"
          git push origin main
